//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NootBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public int AuthorID { get; set; }
        public int FolderID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdationDate { get; set; }
        public bool IsFavorite { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual User User { get; set; }
    }
}
